### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-dynamodb-maven-plugin#26]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@maurezen thank you for the ticket reported, I topped your account for 15 mins, transaction `49998829`

**Comment by dmarkov** [comment]
@romankisilenko please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here; The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by RomanKisilenko** [comment]
Hello, PR merged and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko **30 mins** added to your account (payment number `50597124`), many thanks for your contribution!. +30 to your rating, your total score is +90
