### ISSUE TITLE
UpdateTable operation throws LimitExceededException

### ISSUE THREAD

**Issue by mbomio** [jcabi/jcabi-dynamodb-maven-plugin#34]
Hi, I am trying to update the provisioned throughput for a table changing the throughput from 1 to 300 (read and write). This is what I am doing:
```
String name = "myTable";
AmazonDynamoDBClient client = new AmazonDynamoDBClient(new PropertiesFileCredentialsProvider());
ProvisionedThroughput provisionedThroughput = new ProvisionedThroughput().withReadCapacityUnits(300L)
                    .withWriteCapacityUnits(300L);
client.updateTable(name, provisionedThroughput);
```

This is throwing the following exception:
`
Cannot increase provisioned throughput to more than twice current value (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: LimitExceededException; Request ID: 7a73dc40-bc86-479e-9c4e-a82c9a7f7dfd)
`

I am not seeing this error when updating the throughput in real DynamoDB.

Any thoughts?

Thanks!

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please

**Comment by yegor256** [comment]
@mbomio well, you should see it in real DynamoDB too. Indeed, you can't increase the throughput more than twice in one go. see http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html
