### ISSUE TITLE
New DynamoDB local version 2015-07-16 has released

### ISSUE THREAD

**Issue by ieiayaobb** [jcabi/jcabi-dynamodb-maven-plugin#36]
Please check this url and help to upgrade, thank you.
http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_2015-07-16_1.0.zip

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@ieiayaobb released, see 6a72500 Please check and close the ticket if it works for you

**Comment by ieiayaobb** [comment]
Checked, it's OK now, Thanks a lot
