### ISSUE TITLE
Separate Maven-independent logic so that the project can be used as a library

### ISSUE THREAD

**Issue by esemsch** [jcabi/jcabi-dynamodb-maven-plugin#38]
Hello,

This is a very useful piece of functionality and I believe it may be too tightly coupled with Maven.  Is there any chance the "meat" of the plugin can be separated out from the Maven mojos to a different package so that we can use it as a library?  We would like to run the local dynamo directly from IntelliJ when executing JUnit tests.

Keep up the good work!

Eduard

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@esemsch yes, it's possible, of course. we'll try to do it.

**Comment by esemsch** [comment]
Brilliant, looking forward to it.  Thanks for your great work!

Eduard

**Comment by dmarkov** [comment]
@piddubnyi it's your task, go ahead

**Comment by piddubnyi** [comment]
@esemsch The initial issue is fixed and merged. Additional puzzles added for following refactoring.
Please close this one.

**Comment by esemsch** [comment]
@piddubnyi - thanks a lot, this is brilliant!  Closing this issue now.

**Comment by dmarkov** [comment]
@piddubnyi thanks, I just added **30 mins** to your account, payment `76661197`, 242 hours and 8 mins spent. +30 to your rating, your total score is [+270](http://www.netbout.com/b/35966?open=rating)

**Comment by dmarkov** [comment]
@esemsch once `38-e3be1969`/#52 puzzle is resolved (later, in another ticket), this ticket will be fully complete

**Comment by dmarkov** [comment]
@esemsch the last puzzle `38-e3be1969`/#52 solved

**Comment by alejandroluque** [comment]
Hello all,

Thank you very much for this new feature! But we see that these changes have not been released yet in a new tag, they are in master, is it correct?. In that case, when are you planning to do a new tag in order to work in a stable version?

Thank you in advance and good work!

**Comment by yegor256** [comment]
@rultor release, tag is `0.8`
