### ISSUE TITLE
create-tables goal expects provisioned throughput to be a string not a number

### ISSUE THREAD

**Issue by keithbranton** [jcabi/jcabi-dynamodb-maven-plugin#39]
Thanks for the really useful plugin. Found a minor problem...

When the `aws dynamodb create-table --generate-cli-skeleton` is issued these are numbers.

This difference means I can't use the same file for creating the table in my local environment using `aws dynamodb create-table --cli-input-json table.json`

I realize that you will want to maintain backward compatibility, but it should be easy to change your plugiun to accept either number or text values for these.

I could probably hack together a PR if it would expedite matters.

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@keithbranton thanks for the ticket! Would be great if you can contribute with a pull request!

**Comment by keithbranton** [comment]
This was part of the 0.7.2 release - closing...
