### ISSUE TITLE
RunMojo.java:43-45: Let's avoid code duplication between...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamodb-maven-plugin#42]
Puzzle `41-e81ff08d` in `src/main/java/com/jcabi/dynamodb/maven/plugin/RunMojo.java:43-45` has to be resolved: Let's avoid code duplication between this class and `StartMojo`. One idea is to create a decorator called `ThreadedMojo` that receives another mojo in its constructor and, when called, runs it inside a thread.... The puzzle was created by Denis N. Antonioli on 17-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by dmarkov** [comment]
@jrdalpra please proceed, it's yours

**Comment by dmarkov** [comment]
@yegor256 there is a puzzle in this code `42-3038f9e6`/#46, we'll resolve it later

**Comment by jrdalpra** [comment]
@dmarkov there's no puzzle here https://github.com/jcabi/jcabi-dynamodb-maven-plugin/blob/master/src/main/java/com/jcabi/dynamodb/maven/plugin/RunMojo.java#L43

**Comment by jrdalpra** [comment]
@dmarkov I don't really think that this is a good issue. There's no code duplication here. https://github.com/jcabi/jcabi-dynamodb-maven-plugin/blob/master/src/main/java/com/jcabi/dynamodb/maven/plugin/Instances.java already encapsulates all the work.

**Comment by jrdalpra** [comment]
@denisa can you explain this issue to me? Thanks.

**Comment by pinaf** [comment]
@jrdalpra the difference between `RunMojo` and `StartMojo` seems to be just the threading.

**Comment by denisa** [comment]
StartMojo launches dynamodb on a thread; the thread is killed once the jvm ends.
So, calling mvn dynamodb:start will launch dynamodb, then end the jvm and kill dynmodb

RunMojo launches dynamodb on the main thread.
So, calling mvn dynamodb:run will launch dynamodb and never return.


> On Jan 7, 2016, at 08:55, José V. Dal Prá Junior <notifications@github.com> wrote:
> 
> @denisa <https://github.com/denisa> can you explain this issue to me? Thanks.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/jcabi/jcabi-dynamodb-maven-plugin/issues/42#issuecomment-169727043>.
> 

-- 
Two ways to build software:
 (1) make it so simple that there are obviously no bugs,
 (2) make it so complicated that there are no obvious bugs.
  -- C.A.R. Hoare (1980 Turing Award Lecture)

**Comment by jrdalpra** [comment]
@pinaf @denisa I don't see any difference at both implementation. Both users start method at Instance class. Only differences are the name and the maven build phase. What's the point?

**Comment by pinaf** [comment]
@jrdalpra the difference is that one starts a new thread, the other doesn't.

**Comment by jrdalpra** [comment]
@pinaf I'm not seeing this difference at souce code. Can you show me line? Thanks.

**Comment by pinaf** [comment]
@jrdalpra here's what happened: #43

**Comment by pinaf** [comment]
@yegor256 looks like this issue is invalid as @simonjenga fixed it in another PR (#43)

**Comment by jrdalpra** [comment]
@yegor256  @dmarkov  @pinaf :) That's true. We are trying to solve something that's already solved. :)

**Comment by jrdalpra** [comment]
@dmarkov can you close the issue? thanks.

**Comment by dmarkov** [comment]
@yegor256 Closing, thanks all

**Comment by dmarkov** [comment]
@jrdalpra Much obliged! I have added **1 hour** to your account in payment "AP-3MN93852HE477612F", 49 mins spent... m=49, that's why a bonus here for fast delivery... added +60 to your rating, now it is equal to [+218](http://www.netbout.com/b/36044?open=rating)

**Comment by dmarkov** [comment]
> @dmarkov can you close the issue? thanks.

@jrdalpra closed

**Comment by jrdalpra** [comment]
@dmarkov thanks :)

**Comment by dmarkov** [comment]
> @dmarkov thanks :)

@jrdalpra no problem :)

**Comment by dmarkov** [comment]
@yegor256 last puzzled solved `42-3038f9e6`/#46

**Comment by 0pdd** [comment]
@dmarkov all puzzles are solved

**Comment by 0pdd** [comment]
@dmarkov all puzzles are solved
