### ISSUE TITLE
command line arguments for StartMojo and RunMojo

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-dynamodb-maven-plugin#45]
The command line arguments for ```com.jcabi.dynamodb.maven.plugin.StartMojo``` and ```com.jcabi.dynamodb.maven.plugin.RunMojo``` are not specified anywhere in the project's files or documentation.

These are the same Command line arguments of DynamoDBLocal as indicated in ```com.jcabi.dynamodb.maven.plugin.AbstractDynamoMojo#args()```

An example of a command line argument may be: ```mvn clean package rexsl:run -Drexsl.port=9099 ```

**Comment by dmarkov** [comment]
@yegor256 please dispatch this issue

**Comment by yegor256** [comment]
@simonjenga they are specified here: http://dynamodb.jcabi.com/run-mojo.html
