### ISSUE TITLE
Instances.java:54-54: Let's avoid code duplication between......

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamodb-maven-plugin#46]
Puzzle `42-3038f9e6` in `src/main/java/com/jcabi/dynamodb/maven/plugin/Instances.java:54-54` has to be resolved: Let's avoid code duplication between... The puzzle was created by Simon N on 31-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@piddubnyi the task is yours

**Comment by dmarkov** [comment]
@yegor256 Done, thanks all, closing..

**Comment by dmarkov** [comment]
@piddubnyi I don't see any messages from you above, not sure if there was actual contribution (correct me if I'm wrong)

**Comment by piddubnyi** [comment]
@dmarkov The issue is fixed in #48 and merged. Please close.

**Comment by dmarkov** [comment]
> @dmarkov There was a contribution done in #48

@piddubnyi thanks for that
