### ISSUE TITLE
package-info.java:37-38: Logic of the plugin should...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-dynamodb-maven-plugin#52]
Puzzle `38-e3be1969` in `src/main/java/com/jcabi/dynamodb/core/package-info.java:37-38` has to be resolved: Logic of the plugin should be extracted from maven mojos to this package to allow directly running local dynamodb.... The puzzle was created by Igor Piddubnyi on 29-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@amihaiemil please proceed, it's yours

**Comment by amihaiemil** [comment]
@dmarkov I created PR #54 for this issue. Please assign a reviewr. Thanks.

**Comment by dmarkov** [comment]
@amihaiemil you're holding this task for 15 days already; as a reminder, don't forget to remove the `@todo` puzzle from the source code; -30 added to your rating, current score is: [+15](http://www.netbout.com/b/36402?open=rating)

**Comment by amihaiemil** [comment]
@dmarkov Everything is done already - PR is merged and closed and puzzle removed from the code.

**Comment by amihaiemil** [comment]
@dmarkov Just deploy the PR and this issue can be closed. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #54 for this issue. Please assign a reviewr. Thanks.

@amihaiemil sure

**Comment by amihaiemil** [comment]
@dmarkov  PR #54 is merged and closed. It can be deployed and this issue closed. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov  PR #54 is merged and closed. It can be deployed and this issue closed. Thanks. 

@amihaiemil thanks

**Comment by dmarkov** [comment]
@amihaiemil **30 mins** added to your account (payment number `AP-8N283026917874325`), many thanks for your contribution! 405 hours and 43 mins spent here.; +30 added to your rating, at the moment it is: [+75](http://www.netbout.com/b/36402?open=rating)

**Comment by dmarkov** [comment]
@yegor256 I'm closing the issue...
