### ISSUE TITLE
Abstract method instead of "intentional empty implementation"

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-dynamodb-maven-plugin#55]
In the class ``AbstractDynamoMojo`` there is the method 
```
    /**
     * Set the project environment. This method is intentionally empty!.
     * Implementation to be provided by sub classes.
     * {@link com.jcabi.dynamodb.maven.plugin.AbstractEnviromentMojo}.
     * @throws MojoFailureException If fails
     */
    protected void environment() throws MojoFailureException {
        return;
    }
```

Why not make it abstract and really let all the subclasses implement it and decide whether to give an empty implementation or not?

Making it abstract would mean implementing it also in the classes ``StopMojo`` and ``CreateTablesMojo`` (also overwrite the access modifier since the 2 classes are final and can't have protected methods) .

I tried it locally and the build is successfull.

**Comment by amihaiemil** [comment]
@dmarkov Can you do something about this pls? Thanks.

**Comment by dmarkov** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by dmarkov** [comment]
@amihaiemil thanks for reporting! I topped your account for 15 mins, transaction AP-3J652596RY335922E

**Comment by dmarkov** [comment]
@prondzyn can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by prondzyn** [comment]
@dmarkov PR #58 is ready for this.

**Comment by dmarkov** [comment]
> @dmarkov PR #58 is ready for this.

@prondzyn thanks for that

**Comment by prondzyn** [comment]
@dmarkov I need more time. Still waiting on PR confirmation.

**Comment by dmarkov** [comment]
> @dmarkov I need more time. Still waiting on PR confirmation.

@prondzyn OK, no problem, take your time

**Comment by prondzyn** [comment]
@amihaiemil PR merged. Please close the task.

**Comment by amihaiemil** [comment]
@prondzyn cool, thanks

**Comment by dmarkov** [comment]
@prondzyn Thanks a lot, I just topped your account for **30 mins**, transaction ID `AP-6X588605WY200774V`, total time was 187 hours and 58 mins. +30 added to your rating, at the moment it is: [-30](http://www.netbout.com/b/35715?open=rating)
