### ISSUE TITLE
Release including #38

### ISSUE THREAD

**Issue by agluque** [jcabi/jcabi-dynamodb-maven-plugin#56]
Hello all,

Thank you very much for #38 ! But we see that these changes have not been released yet in a new tag, they are in master, is it correct?. In that case, when are you planning to do a new tag in order to work in a stable version?

Thank you in advance and good work!

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@agluque version 0.8 will be released in #38 thanks for reminding.

**Comment by agluque** [comment]
Thank you very much guys.
