### ISSUE TITLE
Dynamo killing its jvm

### ISSUE THREAD

**Issue by jcogilvie** [jcabi/jcabi-dynamodb-maven-plugin#60]
Using the latest version that this project supports, dynamo is killing its JVM.  I'm hoping that updating to the latest local dynamo can help with this (2016-05-17).  Could you publish that artifact and make whatever changes are necessary in the plugin for compatibility?

[hs_err_pid7079 .txt](https://github.com/jcabi/jcabi-dynamodb-maven-plugin/files/527764/hs_err_pid7079.txt)

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by jcogilvie** [comment]
This was a configuration flaw in our build.  Due to a race condition, the dynamo executable was being overwritten by another dynamo executable while it was running.
