### ISSUE TITLE
Where credentials are defined?

### ISSUE THREAD

**Issue by jherimum** [jcabi/jcabi-dynamodb-maven-plugin#64]
Where credentials are defined?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
You don't need them with DynamoDB Local. Use anything you like.

**Comment by 0crat** [comment]
@yegor256 please, ask @jherimum to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jherimum wait, I'm wrong, you provide credentials in `<configuration>` section of the plugin

**Comment by jherimum** [comment]
Sorry @yegor256 i did not specified the region! everything works fine!
Thanks for the feedback!

Ps. I respect a lot your work man! After reading your posts i started to think OO from other perspective! And its causing a lot of trouble in my job. Its hard to explain to my work colleagues! LOL
