### ISSUE TITLE
"wait" goal

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-dynamodb-maven-plugin#65]
Let's introduce a new goal "wait", which will put the entire plugin on pause, until Ctrl-C is hit.

And let's remove "run".

**Comment by yegor256** [comment]
@rultor release, tag is `0.9`

**Comment by 0crat** [comment]
Oops! Job `gh:jcabi/jcabi-dynamodb-maven-plugin#65` was not in scope
