### ISSUE TITLE
Can we get another official release?

### ISSUE THREAD

**Issue by elruwen** [jcabi/jcabi-dynamodb-maven-plugin#74]
Hi!

There have been some bugfixes merged. Can we get another release published which includes those?

Cheers
Ruwen

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@elruwen[/z](https://www.0crat.com/u/elruwen) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RUBL5H9) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor release, tag is `0.9.2`

**Comment by yegor256** [comment]
@rultor ping

**Comment by yegor256** [comment]
@elruwen version 0.9.2 is in Maven Central

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-dynamodb-maven-plugin#74` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
